# JVM Properties
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
# Mod Properties
mod_id=rolling_gate
mod_name=RollingGate
mod_license=LGPL-3.0 license
mod_version=1.1.0
mod_group_id=dev.anvilcraft.rg
mod_authors=AnvilCraft Development Team
mod_description=A NeoForge mod that controls Minecraft technology options
